name: TranslationAPI
version: ${project.version}
main: br.net.fabiozumbi12.translationapi.TranslationAPI
api-version: 1.13
load: STARTUP
authors: [FabioZumbi12]
description: ${project.description}
commands:
  translationapi:
    permission: 'translationapi.command'
    aliases: trapi
